[package]
name = "moeos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fdt = "0.1"
byteorder = { version = "1", default-features = false }

[build-dependencies]
chrono = "0.4"